version: '3.8'

services:
  bsn-api:
    container_name: bsn-api
    image: ghcr.io/yarozers/bsn-api:1.0.0
    ports:
      - 9090:9090
    networks:
      - spring-demo

networks:
  spring-demo:
    name: spring-demo
    external: true

volumes:
  postgres:
    driver: local
#  строка для запуска workflow
