version: '3.8'  # Версия Docker Compose

services:
  bsn-api:
    container_name: bsn-api  # Имя контейнера
    image: yaroslavozerskiy/bsn-api:1.0.0  # Используемый образ Docker (ваше Java-приложение)
    ports:  # Проброс портов
      - 9090:9090  # Пробрасываем порт 9090 приложения
    networks:  # Сеть, в которой контейнер будет работать
      - spring-demo

networks:
  spring-demo:
    driver: bridge  # Используемый драйвер сети (Bridge - стандартный для Docker)

# Определение томов, используемых для постоянного хранения данных
volumes:
  postgres:
    driver: local  # Используемый драйвер томов (Local - стандартный для Docker)

