services:
  bsn-ui:
    container_name: bsn-ui
    image: yaroslavozerskiy/bsn-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-demo
networks:
  spring-demo:
    driver: bridge  # Используемый драйвер сети (Bridge - стандартный для Docker)
# Определение томов, используемых для постоянного хранения данных
volumes:
  postgres:
    driver: local  # Используемый драйвер томов (Local - стандартный для Docker)
