services:
  bsn-ui:
    container_name: bsn-ui
    image: yaroslavozerskiy/bsn-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-demo

networks:
  spring-demo:
    name: spring-demo  # Явное указание имени сети
    external: true
    driver: bridge

volumes:
  postgres:
    driver: local

