name: BSN Backend API Pipeline

on:
  push:
    branches:
      - main
    paths:
      - book-network/**
      - docker/backend/**
      - 'docker-compose.yml'
      - .github/workflows/*-backend.yml

jobs:
  deployBD:
    name: Deploy BD
    runs-on: self-hosted
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Create deployment folder
        run: |
          echo "Creating deployment folder on server..."
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p ci-cd-bd" || (echo "Error during SSH command" && exit 1)

      - name: Check current directory content
        run: |
          echo "Checking current directory content..."
          ls -la

      - name: Copy docker-compose file
        run: |
          echo "Copying docker-compose file to server..."
          scp -P ${{ secrets.VPS_PORT }} docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:ci-cd-bd/docker-compose.yml || (echo "Error during SCP command" && exit 1)

      - name: Create Docker network
        run: |
          echo "Creating Docker network on server..."
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "docker network create spring-demo || true"

      - name: Set ENV variables and deploy
        run: |
          echo "Setting environment variables and deploying..."
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          export EMAIL_HOST_NAME=${{ secrets.EMAIL_HOST_NAME }}
          export EMAIL_USER_NAME=${{ secrets.EMAIL_USER_NAME }}
          export EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          cd ci-cd-bd
          docker-compose -f docker-compose.yml pull -q
          docker-compose -f docker-compose.yml up -d
          EOF

  compile:
    runs-on: self-hosted
    name: Compile project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: |
          cd book-network
          chmod +x mvnw

      - name: Compile project
        run: |
          cd book-network
          echo "Compiling project..."
          ./mvnw clean compile

  unit-tests:
    runs-on: self-hosted
    name: Unit tests
    needs: [deployBD]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: |
          cd book-network
          chmod +x mvnw

      - name: Running unit Tests
        run: |
          cd book-network
          echo "Running unit tests..."
          ./mvnw clean test

  build:
    runs-on: self-hosted
    name: Build backend
    needs: [ compile, unit-tests ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: |
          cd book-network
          chmod +x mvnw

      - name: Build project
        run: |
          cd book-network
          echo "Building project..."
          ./mvnw clean package

  build-image:
    name: Build Docker image
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: |
          cd book-network
          chmod +x mvnw

      - name: Build project for Docker image
        run: |
          cd book-network
          echo "Building project for Docker image..."
          ./mvnw clean package

      - name: Extract project version
        id: extract_version
        run: |
          cd book-network
          echo "Extracting project version..."
          VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build & Push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: book-network
          file: docker/backend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/yarozers/bsn-api:${{ env.VERSION }},ghcr.io/yarozers/bsn-api:latest
          build-args: |
            PROFILE=dev
            APP_VERSION=${{ env.VERSION }}

  deploy:
    name: Deploy backend
    runs-on: self-hosted
    needs: [build-image]
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Create deployment folder
        run: |
          echo "Creating deployment folder on server..."
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p ci-cd" || (echo "Error during SSH command" && exit 1)

      - name: Check current directory content
        run: |
          echo "Checking current directory content..."
          ls -la

      - name: Copy docker-compose file
        run: |
          echo "Copying docker-compose file to server..."
          scp -P ${{ secrets.VPS_PORT }}  book-network/docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:ci-cd/docker-compose.yml || (echo "Error during SCP command" && exit 1)

      - name: Login to GitHub Container Registry on server
        run: |
          echo "Logging in to GitHub Container Registry on server..."
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GIT_TOKEN }}
          EOF

      - name: Set ENV variables and deploy
        run: |
          echo "Setting environment variables and deploying..."
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          export EMAIL_HOST_NAME=${{ secrets.EMAIL_HOST_NAME }}
          export EMAIL_USER_NAME=${{ secrets.EMAIL_USER_NAME }}
          export EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          cd ci-cd
          docker-compose -f docker-compose.yml pull -q
          docker-compose -f docker-compose.yml up -d
          EOF
